### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by Stellarspace** [Stellarspace/Free-Realms#1]
- [ ] Packets
- [ ] Logs 
- [ ] Patcher
- [ ] Protocols (LibSOE)
- [ ] Web API - Account, Login, RPC, 'ConsumeToken' method, Patcher and Launcher
- [ ] Gateway Server - Login request, Packet analysis, Client version checks, 'ConsumeToken' RPC call, Login reply, Character data and Logout sequence
- [ ] Chunk Server, Object Server, Zone Server and World Server - Basics, Characters, Jobs, Communication, Exploration, Estates, Building, NPCs, Minigames, Quests, Combat
